#!/bin/bash
# $1 is reference tree. $2 is estimated tree
# output to stderr is 
#Splits  Found   xxx     Total   xxx     Frac    0.xxx   MaxLnDf         Ratio           MaxBtDf
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
TREECOMPHOME=$SCRIPT_DIR/tree_comp_morgan
# >&2 echo "perl -I  $TREECOMPHOME $TREECOMPHOME/CompareTree.pl $3 -tree $1 -versus $2 " 
perl -I  $TREECOMPHOME $TREECOMPHOME/CompareTree.pl $3 -tree $1 -versus $2  
